
# mybatis 매핑
mybatis:
  type-aliases-package: com.example.demo.model
  mapper-locations: classpath:mapper/*.xml 
  

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ourmarket275@gmail.com  # 앱 비밀번호를 발급 받은 구글 아이디
    password: vflptrwkfptijqhl
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true

  datasource:
  
# project
    url: jdbc:mysql://43.201.245.48?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 8071
    driver-class-name: com.mysql.cj.jdbc.Driver

  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
#  jpa:
#    open-in-view: true
#    hibernate:
#      ddl-auto: create
#      naming:
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#      use-new-id-generator-mappings: false
#    show-sql: true
#    properties:
#      hibernate.format_sql: true

  jackson:
    serialization:
      fail-on-empty-beans: false
    
server:
  port: 8085
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true



  
  
  
    
  